### ISSUE TITLE
Server crashes when using BetterVillages_MoreVillagers_1.18.2 datapack

### ISSUE THREAD

**Issue by Arqsz** [jtorleonstudios/HUB-Better-Villages#70]
Server crashes when using BetterVillages_MoreVillagers_1.18.2 datapack. See attachment for crash report.
Could you assist in this matter?

[crash-2023-10-04_11.48.00-server.txt](https://github.com/jtorleonstudios/HUB-Better-Villages/files/12802076/crash-2023-10-04_11.48.00-server.txt)

**Comment by jtorleonstudios** [comment]
Ok


```shell
java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.ObjectObjectImmutablePair cannot be cast to class com.mojang.datafixers.util.Pair (it.unimi.dsi.fastutil.objects.ObjectObjectImmutablePair and com.mojang.datafixers.util.Pair are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @62ee68d8)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at com.jtorleonstudios.bettervillage.compat.ICompatProcess.poolReplacementProcess(ICompatProcess.java:75)
	at com.jtorleonstudios.bettervillage.compat.ICompatProcess.lambda$apply$0(ICompatProcess.java:53)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.jtorleonstudios.bettervillage.compat.ICompatProcess.apply(ICompatProcess.java:51)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.lambda$static$0(ServerWorldEvents.java:34)
	at net.minecraft.server.MinecraftServer.redirect$ccn000$fabric-lifecycle-events-v1$onLoadWorld(MinecraftServer.java:7340)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:375)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330)
	at net.minecraft.class_3176.method_3823(class_3176.java:180)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.10.0-10-amd64
