### ISSUE TITLE
Better Villages Crashing on Startup

### ISSUE THREAD

**Issue by Shiumee** [jtorleonstudios/HUB-Better-Villages#98]
Hello, I've noticed everytime I add bettervillages and it's dependency libraryferret into my modpack, it would crash before booting the game. Here is the crash log:
https://pastebin.com/7YsabsJJ

**Comment by Shiumee** [comment]
I am using bettervillages 3.2.0 and libraryferret 4.0.0 for 1.18.2

**Comment by jtorleonstudios** [comment]
We'll check it out, thanks you for your feedback

```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:42) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadableResourceManagerMixin,pl:mixin:APP:pfm.mixins.json:PFMReloadableResourceManagerImplMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.<init>(SimpleReloadInstance.java:42) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10815_(SimpleReloadInstance.java:32) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_203834_(SimpleReloadInstance.java:101) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:45) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,re:classloading,pl:mixin:APP:pollen-common.mixins.json:SimpleReloadableResourceManagerMixin,pl:mixin:APP:pfm.mixins.json:PFMReloadableResourceManagerImplMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23100!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tac.mixins.json:client.MinecraftStaticMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}

```
